context("write")

test_that("can write Makefile", {
  file_path <- tempfile("MakefileR")
  write_makefile(makefile(), file_path)
  expect_identical(readLines(file_path),
                   "# Generated by MakefileR, do not edit by hand")
})
