#' Creates a Makefile
#'
#' A \code{Makefile} consists of a list of rules.
#'
#' @param target Target names as a character vector
#' @param deps Dependency names as a character vector
#' @param script A script to execute to build the targets.
#'
#' @examples
#' create_makefile(create_make_rule("all", c("first_target", "second_target")))
#'
#' @references \url{https://www.gnu.org/software/make/manual/}
#'
#' @importFrom magrittr %>% equals
#' @export
create_makefile <- function(..., .dots = NULL) {
  rules <- c(list(...), .dots)
  stopifnot(lapply(rules, class) %>% lapply(tail, 1L) %>%
              equals("MakefileR_rule"))
  structure(rules, class = "MakefileR_file")
}

#' @export
format.MakefileR_file <- function(x, ...) {
  lapply(x, format) %>%
    Reduce(
      f = function(x, y) c(x, "", y),
      init = c("# Generated by MakefileR, do not edit by hand"))
}

#' @export
print.MakefileR_file <- function(x, ...) {
  cat(paste(format(x), collapse = "\n"))
}

#' @export
c.MakefileR_file <- function(..., recursive = FALSE) {
  rules <- list(...)
  makefile <- rules[[1L]]
  rules <- rules[-1L]
  create_makefile(.dots = c(unclass(makefile), rules))
}
