#' Creates a Makefile
#'
#' A \code{Makefile} consists of a list of rules.
#'
#' @param ... Rules created by \code{\link{make_rule}}
#' @param .dots A list rules in addition to \code{...}
#'
#' @examples
#' makefile(create_make_rule("all", c("first_target", "second_target")))
#'
#' @references \url{https://www.gnu.org/software/make/manual/}
#'
#' @importFrom magrittr %>% equals is_greater_than
#' @export
makefile <- function(..., .dots = NULL) {
  rules <- c(list(...), .dots)
  stopifnot(
    lapply(rules, class) %>%
      sapply(tail, 1L) %>%
      match(c("MakefileR_rule", "MakefileR_def"), 0L) %>%
      is_greater_than(0L)
  )
  structure(rules, class = "MakefileR_file")
}

#' @export
format.MakefileR_file <- function(x, ...) {
  lapply(x, format) %>%
    Reduce(
      f = function(x, y) c(x, "", y),
      init = c("# Generated by MakefileR, do not edit by hand"))
}

#' @export
print.MakefileR_file <- function(x, ...) {
  cat(paste0(format(x), "\n"), sep = "")
}

#' @export
c.MakefileR_file <- function(..., recursive = FALSE) {
  rules <- list(...)
  makefile <- rules[[1L]]
  rules <- rules[-1L]
  makefile(.dots = c(unclass(makefile), rules))
}
